### ISSUE TITLE
Cannot register or login

### ISSUE THREAD

**Issue by BhaskarJoshi-01** [marcorichetta/cs50-project1#1]
![Screenshot from 2020-05-23 00-47-32](https://user-images.githubusercontent.com/56031616/82702117-08326c00-9c8f-11ea-902f-b3d6a50c8fe0.png)
After your home page is loaded,It shows Internal server error 500.I Think there is an issue with database please tell appropriate commands to launch this.
Thanks a lot

**Comment by marcorichetta** [comment]
You need to set up the DB and make the connection before trying to register.

**Comment by BhaskarJoshi-01** [comment]
Thanks...Its working now
