### ISSUE TITLE
Usage of title()

### ISSUE THREAD

**Issue by aswinantony** [marcorichetta/cs50-project1#2]
While querying for ISBN, title, author from books table using the user entered wildcard (Line 161 in application.py) title() is not giving the proper result because there are values in DB which are not in this format.

I would suggest to get rid of that and may be just use ‘ILIKE’ operator in the query instead of ‘LIKE’ in this way the querying would be case-insensitive.

Let me know if this helps or my understanding is incorrect.

**Comment by marcorichetta** [comment]
Hi! You can make a PR or just use the ILIKE operator in your project 

At the time of making this project I didn't know of the case insensitive operator so I just found the way of making the way I knew it.

**Comment by aswinantony** [comment]
Cheers, that's what I did it.
